#!/usr/bin/env bash
#Configure your domain zone

if [ "$#" = 1 ]
then
    subdom=("www" "lb-01" "web-01" "web-02")
    for sub_domain in "${subdom[@]}"
    do
	rec_t=$(dig $sub_domain.$1 | grep -A1 'ANSWER SECTION' | tail -1 | awk '{print $4}')
        des=$(dig $sub_domain.$1 | grep -A1 'ANSWER SECTION' | tail -1 | awk '{print $5}')
	echo "The subdomain $sub_domain is a $rec_t record and points to $des"
    done
elif [ "$#" = 2 ]
then
    rec_t=$(dig $2.$1 | grep -A1 'ANSWER SECTION' | tail -1 | awk '{print $4}')
    des=$(dig $2.$1 | grep -A1 'ANSWER SECTION' | tail -1 | awk '{print $5}')
    echo "The subdomain $2 is a $rec_t record and points to $des"
fi
