#!/usr/bin/env bash
# Configures Ubuntu machine 
apt-get update
apt-get -y install nginx
headers="add_header X-Served-By $HOSTNAME;"
sed -i "20i $headers" /etc/nginx/sites-available/default
service nginx restart
