#!/usr/bin/env bash
# fix nginx webser
pkill apache2
chmod 644 /etc/nginx/nginx.conf
sed -i 's| 80 | 8080 |' /etc/nginx/sites-available/default
sed -i 's|:80 |:8080 |' /etc/nginx/sites-available/default
sudo -u nginx service nginx start
